name: Deploy to production

on:
  push:
    branches: ['main']

jobs:
  # fingerprint:
  #   name: Fingerprint
  #   type: fingerprint
  # get_ios_build:
  #   name: Check for existing ios build    
  #   needs: [fingerprint]
  #   type: get-build
  #   params:
  #     fingerprint_hash: ${{ needs.fingerprint.outputs.ios_fingerprint_hash }}
  #     profile: production  
  build_ios:
    name: Build iOS
    # needs: [get_ios_build]
    # if: ${{ !needs.get_ios_build.outputs.build_id }}
    type: build
    params:
      platform: ios
      profile: production
  submit_ios_build:
    name: Submit iOS Build
    needs: [build_ios]
    type: submit
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}
      profile: production  
  # publish_ios_update:
  #   name: Publish iOS update
  #   environment: production
  #   needs: [get_ios_build]
  #   if: ${{ needs.get_ios_build.outputs.build_id }}
  #   type: update
  #   params:
  #     branch: production
  #     platform: ios
